# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:        
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
        
    - name: ACTIONS_ALLOW_UNSECURE_COMMANDS
      id: ACTIONS_ALLOW_UNSECURE_COMMANDS
      run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV
    
    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2

    # Runs a set of commands using the runners shell
    - name: Run unit tests, check lint issues and generate code-coverage reports
      run: |
        yarn
        yarn run test-all
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        DATOCMS_API_URL: ${{ secrets.DATOCMS_API_URL }}
        DATOCMS_PREVIEW_SECRET: ${{ secrets.DATOCMS_PREVIEW_SECRET }}
        DATOCMS_URL: ${{ secrets.DATOCMS_URL }}
